# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-16 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Студент', 'verbose_name_plural': 'Студенти'},
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('male', 'Чоловіча'), ('female', 'Жіноча')], default='male', max_length=25, verbose_name='Стать'),
        ),
    ]
