# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_student_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Назва')),
                ('teacher', models.CharField(max_length=256, verbose_name='Викладач')),
                ('exam_date', models.DateTimeField(null=True, verbose_name='Дата іспиту')),
                ('duration', models.CharField(blank=True, max_length=256, verbose_name='Тривалість')),
            ],
            options={
                'ordering': ['exam_date'],
                'verbose_name_plural': 'Екзамени',
                'verbose_name': 'Екзамен',
            },
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['title'], 'verbose_name': 'Група', 'verbose_name_plural': 'Групи'},
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.Group', verbose_name='Група'),
        ),
    ]
