# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-01 18:21
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20180426_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100, 'Оцінка не може бути більше 100 балів')], verbose_name='Оцінка')),
                ('notes', models.TextField(blank=True, verbose_name='Додаткові нотатки')),
                ('exam_rating', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.Exam', verbose_name='Екзамен')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.Student', verbose_name='Студент')),
            ],
            options={
                'verbose_name_plural': 'Оцінки',
                'verbose_name': 'Оцінка',
            },
        ),
    ]
