# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-04 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Додаткові нотатки'),
        ),
    ]
