# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-07 12:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0008_auto_20180526_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=128, verbose_name='Заголовок листа')),
                ('message', models.TextField(max_length=2560, verbose_name='Текст повідомлення')),
                ('answer_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата відповіді')),
            ],
            options={
                'verbose_name': 'Відповідь',
                'verbose_name_plural': 'Відповіді',
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.EmailField(max_length=254, verbose_name='Email адреса')),
                ('subject', models.CharField(max_length=128, verbose_name='Заголовок листа')),
                ('message', models.TextField(max_length=2560, verbose_name='Текст повідомлення')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення заявки')),
                ('is_replied', models.BooleanField(default=False, verbose_name='Відправлено')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='slug',
            field=models.SlugField(max_length=256, unique=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='issue',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.Issue'),
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
